#!/bin/bash

FILE="$(basename $(pwd))"
ARG1=./cfg/cliente${1}.config
ARG2=./cfg/cliente${2}.log

#make clean all
echo

dos2unix $ARG1
test -f "./build/$FILE" && valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./build/$FILE $ARG1 $ARG2